# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0feaba0549d6bf943436941ffed456ccca491dd2ba0dffb5d5e078b70b5f4a36be411c4a332799f010a42991af1f8d17a3f9e72c7b8ea5c01c0f26be328817d5

test:
  secret_key_base: 26f6719e858c86c025ab73943455c9aafc7fc8ecd40d4e7381aeddad1a3b09315942047062914a3699425a8783d578a9e5ce46065fec12d6dcb05c9a323626d4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
